### ISSUE TITLE
[Feature Request]Show installation process while `setupSSHD()`

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#28]
The current script shows nothing while installing tubovnc, ngrok, and many other dependencies. We developers don't know whether it gets stucks or anything goes wrong in the background and can only wait for a long time every morning. Please do consider to make the installation process log transparent to users.

**Comment by demotomohiro** [comment]
`setupSSHD()` rarely stuck.
You can see log in 'Runtime' -> 'view runtime logs'.
If all logs were displayed on output cell, finding important message would be very hard.

**Comment by forestfh2** [comment]
> `setupSSHD()` rarely stuck.
> You can see log in 'Runtime' -> 'view runtime logs'.
> If all logs were displayed on output cell, finding important message would be very hard.

We have `!sudo passwd colab` to change the colab password, because I am using bitvise ssh client, I don't want to change the colab password everytime. The other thing is that we really don't need to know the output of `setupSSHD()` because we can write another cell to completely change everything including ngrok port. But the runtime log of google  colab does not automatically refresh itself so....
