### ISSUE TITLE
Lag while using vnc 

### ISSUE THREAD

**Issue by shivamag125** [demotomohiro/remocolab#43]
I am facing lag while moving this setup. Internet speed is about 300Mbps, laptop description: Ubuntu 18.04. 8GB ram, intel core i5 8th gen. 

Any suggestions to speed this up?

**Comment by demotomohiro** [comment]
Open TurboVNC Viewer Options and change Encoding method to `Tight + Medium-Quality JPEG` or `Tight + Low-Quality JPEG(WAN)`.
https://internet-of-tomohiro.netlify.app/google_colab/vnc.en.html#display-smooth-animation

**Comment by shivamag125** [comment]
I tried with these settings. However, it still lags :(

**Comment by demotomohiro** [comment]
- Try different ngrok region. Usually closest one is lowest latency but it can be not always true.

- Find ngrok alternative that is faster than ngrok
You will find web sites that explains these services when you google "ngrok alternative".
You need to modify some code in remocolab to use it.

- Run your own ngrokd server.
https://github.com/inconshreveable/ngrok/blob/master/docs/SELFHOSTING.md
https://github.com/demotomohiro/remocolab/issues/16#issuecomment-619381141

- Buy Google Cloud, AWS or other cloud servers and setup VNC on it
You will get less lag because you can access them without ngrok.
remocolab doesn't work on them because it is designed to work only for Google colab.

**Comment by shivamag125** [comment]
Great! Thanks.
