### ISSUE TITLE
the package lists or status file could not be parsed or opened

### ISSUE THREAD

**Issue by matheus176** [demotomohiro/remocolab#66]
i´m facing this error no matter which script i use to get a colab vps, it started today.
![1122](https://user-images.githubusercontent.com/44915113/96508558-29dd5280-1231-11eb-8f05-2a4c3d20d2f8.png)

**Comment by demotomohiro** [comment]
I tested `remocolab.setupVNC()` on both colab instance with/without GPU now but I didn't got any error.
I think you got that error because ubuntu package server was temporary down.
If you still get same error, please post all error message. You can get more detailed error message by clicking "---- 5 frames ----" line on the error message.
