### ISSUE TITLE
kex_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by localheart7** [demotomohiro/remocolab#79]
How to fix?

**Comment by demotomohiro** [comment]
I think your colab instance was shutdown due to you didn't used google colab for long time.
Please try again.

**Comment by srjsrini** [comment]
Getting the same issue even if i try to connect right after excecution of code.

**Comment by lamhoangtung** [comment]
@demotomohiro I use ngrok to port forward SSH into Google Colab instance regularly and experiencing the same problem.

Some other people have also confirm this issue in this: https://github.com/WassimBenzarti/colab-ssh/issues/45

I'm pretty sure Google had done something from their end since everything suddenly stop working. I already try changing away from the default port 22 and the problem still there. Hope we could share more about resolving this since SSH to colab is a huge thing for my day to day work :3

**Comment by demotomohiro** [comment]
I tested `remocolab.setupSSHD` with ngrok tunnel but I also got error `kex_exchange_identification: Connection closed by remote host` when I tried to login with SSH.
It seems google blocks ngrok.

I also tested `remocolab.setupSSHD` with Argo Tunnel and it worked.
It seems `tunnel = "argotunnel"` is the only way to fix it.

**Comment by lamhoangtung** [comment]
I can confirm that argotunnel still working. Thanks @demotomohiro for the work

**Comment by demotomohiro** [comment]
`remocolab.setupSSHD` with Argo Tunnel works but I got disconnected in 5 minutes after `remocolab.setupSSHD` completed even if I run some code on Google colab's cell.

**Comment by localheart7** [comment]
Ok

**Comment by localheart7** [comment]
ok, thanks

**Comment by ochen1** [comment]
> It seems google blocks ngrok.
> It seems `tunnel = "argotunnel"` is the only way to fix it.

@demotomohiro 

Will Argo Tunnel ever become the default tunnel then?

**Comment by demotomohiro** [comment]
> > It seems google blocks ngrok.
> > It seems `tunnel = "argotunnel"` is the only way to fix it.
> 
> @demotomohiro
> 
> Will Argo Tunnel ever become the default tunnel then?

I changed the default tunnel to Argo Tunnel.
